=== martian-a/greenwood/data/game.dtd
<!ELEMENT game (title?, summary?, players?, starting-hand?, map?, tickets*, related?)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT summary (p*, footnote*)>
<!ELEMENT players (#PCDATA)>
<!ELEMENT starting-hand (cards?)>
<!ELEMENT cards (destinations?)>
<!ELEMENT destinations (#PCDATA)>
<!ELEMENT map (((locations?, routes?, colours)|network?), shortest-paths?)>
<!ELEMENT locations (location*, country*)>
<!ELEMENT country (name?, location*)>
<!ELEMENT location (name?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT routes (route*)>
<!ELEMENT route (location+, colour*)> 
<!ELEMENT colour (name?)>
<!ELEMENT colours (colour*)>
<!ELEMENT tickets (ticket*)>
<!ELEMENT ticket (location*, country*, note?)>
<!ELEMENT note (#PCDATA)>
<!ELEMENT network (nodes, edges)>
<!ELEMENT nodes (node+)> 
<!ELEMENT edges (edge+)>
<!ELEMENT node (name?)>
<!ELEMENT edge (node, node)>
<!ELEMENT shortest-paths (path+)>
<!ELEMENT path (location, location, via*)>
<!ELEMENT via (location*)>
<!ELEMENT related (link*)>
<!ELEMENT link (title?, description?, img*)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT img EMPTY>
<!ELEMENT p (#PCDATA)*>

<!ATTLIST game 
	id ID #REQUIRED
	publish (true|false) "true">
<!ATTLIST map
	seed CDATA #IMPLIED>
<!ATTLIST country 
	id ID #IMPLIED
	ref IDREF #IMPLIED
	points CDATA #IMPLIED>
<!ATTLIST location 
	id ID #IMPLIED
	ref IDREF #IMPLIED
	points CDATA #IMPLIED
	x CDATA #IMPLIED
	y CDATA #IMPLIED>
<!ATTLIST name
	sort CDATA #IMPLIED>
<!ATTLIST route 
	length (1|2|3|4|5|6|8) #REQUIRED
	colour IDREF #IMPLIED
	tunnel (true|false) "false"
	ferry  (0|1|2) "0"
	microlight (true|false) "false">
<!ATTLIST colour 
	id ID #IMPLIED
	ref IDREF #IMPLIED>
<!ATTLIST ticket 
	points CDATA #IMPLIED>
<!ATTLIST node
	id ID #IMPLIED
	ref IDREF #IMPLIED>
<!ATTLIST edge
	id ID #IMPLIED
	length CDATA #IMPLIED>
<!ATTLIST path
	distance CDATA #IMPLIED>
<!ATTLIST via
	direct (true|false) "false">
<!ATTLIST players
	min (2|4) "2"
	max (3|4|5|6|7) "5"
	double-routes-min (3|4|5) "4">
<!ATTLIST starting-hand
	carriages (40|45) "45"
	stations (0|3) "0">
<!ATTLIST cards
	train (4) "4">
<!ATTLIST destinations
	regular (1|2|3|4|5) "3"
	long (1|2|3|4|5) "1"
	must-keep (1|2|3|4|5) "2">
<!ATTLIST link
	href CDATA #REQUIRED>
<!ATTLIST img
	class CDATA #IMPLIED
	border (0|1) "0"
	src CDATA #REQUIRED
	height CDATA #IMPLIED
	width CDATA #IMPLIED>

=== martian-a/greenwood/data/game.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE game SYSTEM "game.dtd">
<game id="TTR">
   <map>
      <colours>
         <colour id="RED">
            <name>Red</name>
         </colour>
         <colour id="ORA">
            <name>Orange</name>
         </colour>
         <colour id="YEL">
            <name>Yellow</name>
         </colour>
         <colour id="GRN">
            <name>Green</name>
         </colour>
         <colour id="BLU">
            <name>Blue</name>
         </colour>
         <colour id="VIO">
            <name>Pink</name>
         </colour>
         <colour id="WHI">
            <name>White</name>
         </colour>
         <colour id="BLA">
            <name>Black</name>
         </colour>
         <colour id="GRY">
            <name>Grey</name>
         </colour>
      </colours>
   </map>
 </game>

=== martian-a/greenwood/data/nordic.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE game SYSTEM "game.dtd">
<game id="NOR">
	<title>Nordic</title>
	<players max="3" double-routes-min="3" />
	<starting-hand carriages="40">
		<cards>
			<destinations regular="5" />
		</cards>
	</starting-hand>
   <map>
      <locations>
         <location id="HON">
            <name>Honningsvåg</name>
         </location>
         <location id="KIR">
            <name>Kirkenes</name>
         </location>
         <location id="MUR">
            <name>Murmansk</name>
         </location>
         <location id="LIE">
            <name>Lieska</name>
         </location>
         <location id="KAJ">
            <name>Kajaani</name>
         </location>
         <location id="OUL">
            <name>Oulu</name>
         </location>
         <location id="TOR">
            <name>Tornio</name>
         </location>
         <location id="ROV">
            <name>Rovaniemi</name>
         </location>
         <location id="BOD">
            <name>Boden</name>
         </location>
         <location id="KIR2">
            <name>Kiruna</name>
         </location>
         <location id="TRO">
            <name>Tromsø</name>
         </location>
         <location id="NAR">
            <name>Narvik</name>
         </location>
         <location id="MOI">
            <name>Mo I Rana</name>
         </location>
         <location id="TRO2">
            <name>Trondheim</name>
         </location>
         <location id="OST">
            <name>Östersund</name>
         </location>
         <location id="UME">
            <name>Umeå</name>
         </location>
         <location id="VAS">
            <name>Vassa</name>
         </location>
         <location id="KUO">
            <name>Kuopio</name>
         </location>
         <location id="IMA">
            <name>Imatra</name>
         </location>
         <location id="LAH">
            <name>Lahti</name>
         </location>
         <location id="TAM">
            <name>Tampere</name>
         </location>
         <location id="TUR">
            <name>Turku</name>
         </location>
         <location id="HEL">
            <name>Helsinki</name>
         </location>
         <location id="TAL">
            <name>Talinn</name>
         </location>
         <location id="STO">
            <name>Stockholm</name>
         </location>
         <location id="NKP">
            <name>Norrköping</name>
         </location>
         <location id="KAR">
            <name>Kariskrona</name>
         </location>
         <location id="KOB">
            <name>København</name>
         </location>
         <location id="ARH">
            <name>Århus</name>
         </location>
         <location id="ALB">
            <name>Ålborg</name>
         </location>
         <location id="GOT">
            <name>Göteborg</name>
         </location>
      </locations>
      <colours>
         <colour id="RED">
            <name>Red</name>
         </colour>
         <colour id="ORA">
            <name>Orange</name>
         </colour>
         <colour id="YEL">
            <name>Yellow</name>
         </colour>
         <colour id="GRN">
            <name>Green</name>
         </colour>
         <colour id="BLU">
            <name>Blue</name>
         </colour>
         <colour id="VIO">
            <name>Pink</name>
         </colour>
         <colour id="WHI">
            <name>White</name>
         </colour>
         <colour id="BLA">
            <name>Black</name>
         </colour>
         <colour id="GRY">
            <name>Grey</name>
         </colour>
      </colours>
   </map>
 </game>
